live_config_reload = true

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Comic Mono"
style = "Bold"

[font.bold_italic]
family = "Comic Mono"
style = "Bold Italic"

[font.italic]
family = "Comic Mono"
style = "Italic"

[font.normal]
family = "Comic Mono"
style = "Regular"

[window]
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 5
y = 5
