# Machine policy: per-host speaker DSP correction for tempest's built-in speakers.
#
# The Framework 13 chassis fires its speakers downward, which makes them sound
# thin and resonant. cab404's measured EasyEffects chain (the "Gracefu's Edits"
# profile + a 27 dB convolution impulse response) corrects that. See
# https://github.com/cab404/framework-dsp and the Arch wiki Framework 13 page.
#
# Note: cab404 targets the Ryzen 7040 mainboard; tempest is the AMD AI 300 board.
# The chassis and speaker drivers are shared across mainboard generations and the
# DSP runs after the codec, so the correction transfers — but it is not validated
# for this board, so treat the vendored preset as a starting point and tune by ear.
# Because we vendor (not pin upstream), the JSON in ./easyeffects is yours to edit.
#
# This stays out of the (portable) niri rice on purpose: it is hardware-specific to
# this laptop's drivers. See CONTEXT.md, "machine policy".
{...}: let
  presetName = "framework-speakers";
  irFile = "IR_22ms_27dB_5t_15s_0c.irs";

  # EasyEffects 8 autoloads by matching a file "<node>:<route>.json" in autoload/output/
  # against the active output's PipeWire node name and route, then loading that file's
  # "preset-name" (presets_autoload_manager.cpp: find()/getFilePath() read ONLY
  # "preset-name"; the "device"/"device-description" fields are cosmetic). tempest's
  # built-in audio is the Realtek ALC285 codec on the node below, which carries two
  # routes: "Speakers" and "Headphones" (the 3.5mm jack).
  #
  # We bind BOTH built-in routes declaratively: Speakers -> the correction, Headphones
  # -> a flat passthrough (the downward-firing-speaker IR has no business on the jack).
  # Everything else (AirPods, the CalDigit dock, HDMI) is a different node with no entry.
  # EasyEffects does NOT clear the active preset when it moves to an entry-less device:
  # it loads the autoload *fallback*, and only if the fallback is enabled (defaults off).
  # So to keep the chain off those too, set framework-flat as the OUTPUT autoload fallback
  # and enable it once in the GUI (Preset Autoloading tab). That flag lives in EE's Qt
  # settings db (~/.config/easyeffects/db — on /persist, so it survives reboots), not in
  # gsettings/Nix; hence a one-time toggle. If the chain mis-engages, confirm these
  # node/route strings against `wpctl inspect` and `journalctl --user -u easyeffects`.
  speakerNode = "alsa_output.pci-0000_c1_00.6.analog-stereo";
  speakerRoute = "Speakers";
  headphoneRoute = "Headphones"; # 3.5mm jack: same node, flat (no speaker IR)
  speakerDesc = "Ryzen HD Audio Controller Analog Stereo";
  flatName = "framework-flat";

  # One autoload binding: a route on the built-in node -> a preset name.
  mkOutputAutoload = route: preset: {
    name = "easyeffects/autoload/output/${speakerNode}:${route}.json";
    value.text = builtins.toJSON {
      device = speakerNode;
      "device-description" = speakerDesc;
      "device-profile" = route;
      "preset-name" = preset;
    };
  };
in {
  services.easyeffects = {
    enable = true;
    # No top-level `preset`: nothing is force-loaded at startup; autoload drives it.
    extraPresets = {
      # The speaker correction. Parsed from the vendored JSON and regenerated by Home
      # Manager, so it lives as derived Nix data rather than an opaque imported dotfile.
      ${presetName} =
        builtins.fromJSON (builtins.readFile ./easyeffects/framework-speakers.json);

      # Empty passthrough. Bound to the Headphones route below, and meant to be the OUTPUT
      # autoload *fallback* (set + enabled once in the GUI's Preset Autoloading tab) so the
      # chain stays off every node without its own entry — AirPods/HDMI/dock. Without that
      # fallback enabled, EasyEffects keeps the last preset loaded on an entry-less device,
      # so the speaker chain leaks. Result once configured: built-in speakers ->
      # framework-speakers, everything else -> flat.
      ${flatName} = { output = { blocklist = [ ]; plugins_order = [ ]; }; };
    };
  };

  # The convolver's measured impulse response (a measurement, so a pinned binary that
  # can't be derived; referenced by kernel-name, resolved against this irs/ directory),
  # plus the two per-route autoload bindings for the built-in node: Speakers -> the
  # correction, Headphones (3.5mm jack) -> flat, so the speaker IR never colours the jack.
  xdg.dataFile = builtins.listToAttrs [
    (mkOutputAutoload speakerRoute presetName)
    (mkOutputAutoload headphoneRoute flatName)
  ] // {
    "easyeffects/irs/${irFile}".source = ./easyeffects/${irFile};
  };
}
